language: php
php:
    - 7.1
services:
    - elasticsearch
before_script:
    - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
    - composer install
script:
    - vendor/bin/phpunit
